### PR TITLE
Create NvidiaDriversInstallation

### PR DESCRIPTION
**Pull request by jupeuk**
Hi, Please consider merging this document on Nvidia driver installation into the Ubuntu Server and Desktop documentation, see the linked article in the community wiki. This has been written collectively by members of the support team and Nvidia. 

SE contact: [Victor Vavan](https://directory.canonical.com/orgchart/Victor%20Vavan/)

Thanks!
BR Juliane

### CODE REVIEW

**Comment by pmatulis** [comment]
@s-makin Can you look at this request to relocate Support documentation to the Ubuntu Server Guide? It looks like the Desktop is tagged too. I'm not sure what to do about that aspect.

**Comment by jupeuk** [comment]
Hi Sally, I just want to follow up whether there's any progress on this one. Please let us know if you need any additional information, or feel free to schedule a meeting with me and Victor.
Thanks, Juliane

**Comment by s-makin** [comment]
> Hi Sally, I just want to follow up whether there's any progress on this one. Please let us know if you need any additional information, or feel free to schedule a meeting with me and Victor. Thanks, Juliane

Hi Juliane, 

Sorry for the delay. This isn't a straightforward case, and there's still an ongoing/open question about whether the Server Guide is the right place for this content. 

Since it includes some content that would better belong in the Desktop docs (and they don't have public facing documentation as we do), we have to decide firstly whether we would host the whole thing, or just the parts relevant to us (in which case, what should happen to the rest?). I think this question would also need the Desktop team's input to resolve.

We also don't currently have a section that the content could feasibly belong in, so if we moved it as-is it would exist randomly by itself (which I would like to avoid). There's an argument to be made that we could include it in a section about ML/Ops etc, but that content doesn't exist yet and would need to be added to the roadmap for next cycle.

However, the largest question in my mind is whether it belongs in product documentation at all (since it can always be posted to the forum without being part of the docs). Our docs don't currently have any content/guides about proprietary software/hardware, so we need to decide whether moving away from that is a step we want to take. In which case, we'd need to start providing doc support for other non-open-source products that are related to Ubuntu Server in some way. Since the content was co-written with Nvidia, it might be more appropriate for them to host it in their own documentation (there is a [precedent for this](https://docs.nvidia.com/datacenter/tesla/tesla-installation-notes/index.html#ubuntu-lts)). 

Let me know your thoughts. 

Sally

**Comment by vicvavan** [comment]
Hello Sally,

I discussed your comment with our Nvidia TAM as well as some Nvidia folk. They are pretty adamant about hosting the documentation on our infrastructure rather than Nvidia's, as this is a guide specifically for Ubuntu using Canonical tools such as `ubuntu-drivers`.

We receive a lot of cases regarding driver installation and it seems too informal (unlike a KB or our official domain) to direct our customers to the community wiki or a forum that often. We also believe a KB is not appropriate for this information, as customers should not need to come asking for it. Thus, our conclusion is that it should be available on our official domain through a quick Google search. 

Furthermore, we would require someone from the documentation team rather than Support Engineering to take ownership of this documentation, as the information will be changing somewhat frequently. As an example, the 535 driver has already been released, so the documentation is already outdated. I suppose this could also be solved using a variable rather than specific version numbers.  

We are not sure what input to give on the general composition and organization of the information, such as how it should be divided (server/desktop, etc.) as this inherently seems like a decision for the documentation team. Any decisions made here by the documentation team will more than likely be acceptable on our side, as long as the information is available. 

Kind regards,
-Victor

**Comment by s-makin** [comment]
Dear all, 

Following on from all the discussions, I can confirm that the page in question has been converted to Markdown and published in the Server Guide.

To host it, we have created a new topic called "Graphics", and in Riga we will have a team discussion about other content we can use to populate it with. For now, the Nvidia page is joined by content we already had about virtual graphics. For future reference, the links to the pages in question are:

* [NVIDIA drivers installation](https://ubuntu.com/server/docs/nvidia-drivers-installation) (documentation page)
* [Corresponding Discourse post](https://discourse.ubuntu.com/t/nvidia-drivers-installation/39022), which has had a cursory edit for style to make it look and feel like our other documentation. The content is, however, unchanged from what's on the wiki. If you would like reviews at any point on future edits, please feel free to ping me on Mattermost.

Note that I have not updated the wiki page to provide a redirect.

**Comment by pmatulis** [comment]
Outstanding @s-makin - I'll mark this request as closed by merging the PR.

@vicvavan Can you ensure that the wiki edition gets deprecated with a top banner and a link redirecting visitors to the new page's location? I tried doing this but I encountered permission issues. Thank you.

**Comment by vicvavan** [comment]
@pmatulis It seems I also don't have the appropriate permissions to edit the community wiki (any longer). I will seek permissions and then deprecate the page as requested. Stand by for an update...

**Comment by vicvavan** [comment]
I managed to get permission fairly quickly and edit the community wiki page. Please let me know if it is alright, or if you would like it altered.

**Comment by pmatulis** [comment]
@vicvavan I also got the necessary permissions. I reworded/reformatted a little.

**Pull request merged**
